# Generated by Django 5.2.1 on 2025-08-26 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staffRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('f_h', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='phone must be 10 digits')])),
                ('password', models.CharField(max_length=25)),
                ('confirm_password', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=1)),
                ('zip', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='pin code must be 6 digits ')])),
                ('adhar', models.FileField(upload_to='adhar/')),
                ('pan', models.FileField(upload_to='pan/')),
                ('agree', models.BooleanField(default=False, help_text='Must agree to terms & conditions')),
            ],
        ),
    ]
