# Generated by Django 5.2.1 on 2025-08-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0002_country_staffregistrationmodel_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='counrty',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
