# Generated by Django 5.2.1 on 2025-08-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0003_rename_counrty_state_country_alter_country_name'),
        ('superadmin', '0002_rolemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.rolemodel'),
        ),
    ]
