# Generated by Django 5.1.4 on 2025-08-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0004_staffregistrationmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
