# Generated by Django 5.1.4 on 2025-08-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0005_alter_staffregistrationmodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffregistrationmodel',
            name='address',
        ),
    ]
