# Generated by Django 5.1.4 on 2025-08-30 10:11

import staffPortal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0006_remove_staffregistrationmodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='adhar',
            field=models.FileField(upload_to=staffPortal.models.adhar_upload_path),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='confirm_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='pan',
            field=models.FileField(upload_to=staffPortal.models.pan_upload_path),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
