# Generated by Django 5.1.4 on 2025-08-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0007_loginmodel_alter_staffregistrationmodel_adhar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffregistrationmodel',
            old_name='zip',
            new_name='pincode',
        ),
        migrations.RemoveField(
            model_name='staffregistrationmodel',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Control Staff login access'),
        ),
    ]
