# Generated by Django 5.1.4 on 2025-08-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0008_rename_zip_staffregistrationmodel_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
