# Generated by Django 5.1.4 on 2025-09-04 16:30

import django.core.validators
import staffPortal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0009_staffregistrationmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='college',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='highest_qualification',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='notice_period',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='passing_year',
            field=models.IntegerField(blank=True, default='2000', max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Year must in 4 digits')]),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='percentage',
            field=models.FloatField(blank=True, default='7.5', null=True),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='salary',
            field=models.IntegerField(blank=True, default='1000', null=True),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='salary_slip',
            field=models.FileField(default='', null=True, upload_to=staffPortal.models.salary_slip_upload_path),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='total_experience',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffregistrationmodel',
            name='work_status',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
