# Generated by Django 5.1.4 on 2025-09-04 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0010_staffregistrationmodel_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='passing_year',
            field=models.IntegerField(blank=True, default=2000, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
