# Generated by Django 5.1.4 on 2025-09-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0013_alter_staffregistrationmodel_passing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='passing_year',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
