# Generated by Django 5.1.4 on 2025-09-04 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0014_alter_staffregistrationmodel_passing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='passing_year',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Year must be in 4 digits')]),
        ),
    ]
