# Generated by Django 5.1.4 on 2025-09-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0017_auto_20250904_2241'),
    ]

    operations = [
    ]
