# Generated by Django 5.1.4 on 2025-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0019_auto_20250904_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='percentage',
            field=models.FloatField(blank=True, default=7.5, null=True),
        ),
    ]
