# Generated by Django 5.1.4 on 2025-09-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0021_alter_staffregistrationmodel_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='salary',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
