# Generated by Django 5.1.4 on 2025-09-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0022_alter_staffregistrationmodel_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='percentage',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
