# Generated by Django 5.1.4 on 2025-09-07 11:30

import staffPortal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0023_alter_staffregistrationmodel_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='salary_slip',
            field=models.FileField(null=True, upload_to=staffPortal.models.salary_slip_upload_path),
        ),
    ]
