# Generated by Django 5.1.4 on 2025-09-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0024_alter_staffregistrationmodel_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffPortal.city'),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffPortal.country'),
        ),
        migrations.AlterField(
            model_name='staffregistrationmodel',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffPortal.state'),
        ),
    ]
