# Generated by Django 5.2.1 on 2025-09-20 11:04

import django.core.validators
import django.db.models.deletion
import staffPortal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0025_alter_staffregistrationmodel_city_and_more'),
        ('superadmin', '0005_alter_studentcourses_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnquiryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('f_h', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='phone must be 10 digits')])),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='pin code must be 6 digits ')])),
                ('highest_qualification', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('college_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('branch_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('passing_year', models.CharField(blank=True, default=None, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Year must be in 4 digits')])),
                ('percentage', models.FloatField(blank=True, default=None, null=True)),
                ('work_status', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('total_experience', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('job_title', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('notice_period', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('adhar', models.FileField(upload_to=staffPortal.models.adhar_upload_path)),
                ('salary_slip', models.FileField(null=True, upload_to=staffPortal.models.salary_slip_upload_path)),
                ('agree', models.BooleanField(default=False, help_text='Must agree to terms & conditions')),
                ('directors_meeting', models.BooleanField(default=False, help_text='Meeting with director')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffPortal.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffPortal.country')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.studentcourses')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffPortal.state')),
            ],
        ),
    ]
