# Generated by Django 5.2.6 on 2025-09-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0026_studentenquirymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquirymodel',
            name='Enquiry_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffPortal.staffregistrationmodel'),
        ),
    ]
