# Generated by Django 5.2.1 on 2025-11-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0027_studentenquirymodel_enquiry_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainersClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
                ('startingTime', models.TimeField(null=True)),
                ('endingTime', models.TimeField(null=True)),
                ('startingDate', models.DateField(null=True)),
            ],
        ),
    ]
