# Generated by Django 5.2.1 on 2025-12-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffPortal', '0028_trainersclassschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquirymodel',
            name='is_recent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentenquirymodel',
            name='remark',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
