# Generated by Django 5.1.4 on 2025-09-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_rolemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=100)),
            ],
        ),
    ]
