# Generated by Django 5.1.4 on 2025-09-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_studentcourses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourses',
            old_name='courses',
            new_name='course',
        ),
    ]
