# Generated by Django 5.1.4 on 2025-09-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_rename_courses_studentcourses_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourses',
            name='course',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
